import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://demoblaze.com/');
  await page.getByRole('link', { name: 'Log in' }).click();
  await page.locator('#loginusername').click();
  await page.locator('#loginusername').fill('Lanka');
  await page.locator('#loginpassword').fill('Lanka123#');
  await page.getByRole('button', { name: 'Log in' }).click();
});

import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('chrome-error://chromewebdata/');
  await page.getByRole('button', { name: 'Advanced' }).click();
  await page.getByRole('link', { name: 'Proceed to localhost (unsafe)' }).click();
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'example@mail.com' }).click();
  await page.getByRole('textbox', { name: 'example@mail.com' }).fill('admin@mail.com');
  await page.getByRole('textbox', { name: '********' }).click();
  await page.getByRole('textbox', { name: '********' }).fill('12345678');
  await page.getByRole('button', { name: 'Login account' }).click();
  await page.getByRole('link', { name: 'Students ' }).click();
  await page.getByRole('link', { name: 'Add Student' }).click();
  await page.getByLabel('General').getByText('Choose Option').click();
  await page.getByRole('treeitem', { name: 'Active', exact: true }).click();
  await page.getByLabel('General').locator('div').filter({ hasText: 'Employability Guarantee' }).locator('span').click();
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('Lanka');
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).fill('Prasadini');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('lanka+60@thesanmark.com');
  await page.getByRole('spinbutton', { name: 'Phone Number' }).click();
  await page.getByRole('spinbutton', { name: 'Phone Number' }).fill('1234567890');
  await page.getByRole('button', { name: 'Save Details' }).click();
  await page.getByRole('tab', { name: 'Personal' }).click();
  await page.getByPlaceholder('Date of Birth').fill('2025-06-01');
  await page.locator('#select2-gender-container').click();
  await page.getByRole('treeitem', { name: 'Male', exact: true }).click();
  await page.getByText('Date of Birth Gender Gender').click();
  await page.getByRole('textbox', { name: 'NIC / Passport' }).click();
  await page.getByRole('textbox', { name: 'NIC / Passport' }).fill('112233456V');
  await page.getByRole('textbox', { name: 'Nationality' }).click();
  await page.getByRole('textbox', { name: 'Nationality' }).fill('Sinhala');
  await page.getByRole('textbox', { name: 'Certificate Name' }).click();
  await page.getByRole('textbox', { name: 'Certificate Name' }).fill('ISQTB');
  await page.getByRole('textbox', { name: 'Full Name' }).click();
  await page.getByRole('textbox', { name: 'Full Name' }).fill('Lanka Prasadini');
  await page.getByRole('textbox', { name: 'Address' }).click();
  await page.getByRole('textbox', { name: 'Address' }).fill('kahatapitiya, Batapola');
  await page.getByRole('textbox', { name: 'City' }).click();
  await page.getByRole('textbox', { name: 'City' }).fill('Ambalangoda');
  await page.getByRole('textbox', { name: 'Postal/ZIP Code' }).click();
  await page.getByRole('textbox', { name: 'Postal/ZIP Code' }).fill('12345');
  await page.getByRole('button', { name: 'Save Details' }).click();
  await page.getByRole('tab', { name: 'Work & Education' }).click();
  await page.getByRole('textbox', { name: 'Occupation' }).click();
  await page.getByRole('textbox', { name: 'Occupation' }).fill('Engineer');
  await page.getByRole('textbox', { name: 'Field' }).click();
  await page.getByRole('textbox', { name: 'Field' }).fill('erer');
  await page.getByLabel('Work & Education').getByText('Choose Option').click();
  await page.getByRole('treeitem', { name: '3 + years' }).click();
  await page.getByRole('textbox', { name: 'Company' }).click();
  await page.getByRole('textbox', { name: 'Company' }).fill('erwer');
  await page.getByRole('textbox', { name: 'Job Title' }).click();
  await page.getByRole('textbox', { name: 'Job Title' }).fill('ewrwer');
  await page.getByRole('textbox', { name: 'Education Statement' }).click();
  await page.getByRole('textbox', { name: 'Education Statement' }).fill('rer');
  await page.getByRole('textbox', { name: 'Highest Qualification' }).click();
  await page.getByRole('textbox', { name: 'Highest Qualification' }).fill('werwer');
  await page.getByRole('textbox', { name: 'A/L Sylabus' }).click();
  await page.getByRole('textbox', { name: 'A/L Sylabus' }).fill('erwer');
  await page.getByRole('textbox', { name: 'Years', exact: true }).click();
  await page.getByRole('textbox', { name: 'Years', exact: true }).fill('2');
  await page.getByRole('textbox', { name: 'Stream' }).click();
  await page.getByRole('textbox', { name: 'Stream' }).fill('fgdfg');
  await page.getByRole('textbox', { name: 'Subject 1' }).click();
  await page.getByRole('textbox', { name: 'Subject 1' }).fill('fgfdg');
  await page.getByRole('textbox', { name: 'Subject 2' }).click();
  await page.getByRole('textbox', { name: 'Subject 2' }).fill('fgfg');
  await page.getByRole('textbox', { name: 'Subject 3' }).click();
  await page.getByRole('textbox', { name: 'Subject 3' }).fill('fgfg');
  await page.getByRole('button', { name: 'Save Details' }).click();
  await page.getByRole('tab', { name: 'Uploads' }).click();
  await page.getByRole('tab', { name: 'Next' }).click();
  await page.locator('#batchId').selectOption('1');
  await page.getByRole('radio', { name: 'LKR Price' }).check();
});

